import { NextResponse } from 'next/server';
import { getDB } from '@/db';

export async function GET(
  req: Request,
  { params }: { params: { uniqueCode: string } }
) {
  try {
    const db = await getDB();
    const { uniqueCode } = await params;
    const accept = req.headers.get('accept') || '';
    
    // Get client IP
    const forwardedFor = req.headers.get('x-forwarded-for');
    const ipAddress = forwardedFor ? forwardedFor.split(',')[0] : 'unknown';
    const userAgent = req.headers.get('user-agent') || 'unknown';
    
    const record = await db.getQRByCode(uniqueCode);
    
    // Handle NOT FOUND
    if (!record) {
      if (accept.includes('application/json')) {
        return NextResponse.json({
          error: true,
          code: 'QR_NOT_FOUND',
          message: 'This QR code was not generated by TalentYug systems or does not exist.',
          statusCode: 404
        }, { status: 404 });
      }
      return new NextResponse(
        `<html><body style="font-family: sans-serif; text-align: center; padding: 50px;">
          <h1>404 - Not Found</h1>
          <p>This QR code was not generated by TalentYug systems or does not exist.</p>
        </body></html>`,
        { status: 404, headers: { 'Content-Type': 'text/html' } }
      );
    }
    
    // Handle INACTIVE
    if (!record.isActive) {
      if (accept.includes('application/json')) {
        return NextResponse.json({
          error: true,
          code: 'QR_DEACTIVATED',
          message: 'QR code has been deactivated.',
          statusCode: 403
        }, { status: 403 });
      }
      return new NextResponse(
        `<html><body style="font-family: sans-serif; text-align: center; padding: 50px;">
          <h1>QR Code Deactivated</h1>
          <p>This QR code has been deactivated and is no longer valid.</p>
        </body></html>`,
        { status: 403, headers: { 'Content-Type': 'text/html' } }
      );
    }
    
    // ACTIVE QR - Record Scan
    await db.incrementScan(uniqueCode, { ipAddress, userAgent });
    
    // Fetch fresh record for accurate scan count in response
    const freshRecord = await db.getQRByCode(uniqueCode);
    
    const jsonResponse = {
      status: 'verified',
      uniqueCode: record.uniqueCode,
      label: record.label || null,
      originalUrl: record.originalUrl,
      createdAt: record.createdAt,
      scanCount: freshRecord?.scanCount || record.scanCount + 1,
      isActive: record.isActive
    };
    
    if (accept.includes('application/json')) {
      return NextResponse.json(jsonResponse, { status: 200 });
    }
    
    // HTML Response with Auto-Redirect
    const html = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>QR Verified - Redirecting...</title>
        <meta http-equiv="refresh" content="3;url=${record.originalUrl}">
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body class="bg-gray-50 flex items-center justify-center min-h-screen">
        <div class="bg-white p-8 rounded-2xl shadow-xl text-center max-w-md w-full border border-gray-100">
          <div class="w-16 h-16 bg-green-100 text-green-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
          </div>
          <h1 class="text-2xl font-bold text-gray-800 mb-2">Verified Successfully</h1>
          <p class="text-gray-500 mb-6">This QR code is authentic.</p>
          <div class="bg-gray-50 rounded-lg p-4 mb-6 text-sm text-left text-gray-600">
            <p><span class="font-semibold">Code:</span> ${record.uniqueCode}</p>
            ${record.label ? `<p><span class="font-semibold">Label:</span> ${record.label}</p>` : ''}
            <p><span class="font-semibold">Scans:</span> ${jsonResponse.scanCount}</p>
          </div>
          <p class="text-sm text-gray-400">Redirecting you to the destination in 3 seconds...</p>
          <a href="${record.originalUrl}" class="mt-4 inline-block text-blue-500 hover:underline text-sm">Click here if not redirected</a>
        </div>
        <script>
          setTimeout(function() {
            window.location.href = "${record.originalUrl}";
          }, 3000);
        </script>
      </body>
      </html>
    `;
    
    return new NextResponse(html, { 
      status: 200, 
      headers: { 'Content-Type': 'text/html' } 
    });
    
  } catch (error) {
    console.error('Verify QR Error:', error);
    return NextResponse.json({
      error: true,
      code: 'INTERNAL_SERVER_ERROR',
      message: 'Failed to verify QR code.',
      statusCode: 500
    }, { status: 500 });
  }
}
